[workspace]
members = [
    "crash_backend",
    "plinko_backend",
    "dice_backend",
    "roulette_backend",
    "life1_backend",
    "life_core",
    "life_simulation",
]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1